In [1]:
import requests
import json
import pandas as pd

In [2]:
API_KEY = '20sodZ8XOxJvfbreRnTFONeTUQF'

In [3]:
urls = {'https://api.glassnode.com/v1/metrics/market/price_usd_close',
        'https://api.glassnode.com/v1/metrics/distribution/exchange_net_position_change',
        'https://api.glassnode.com/v1/metrics/indicators/reserve_risk', 
        'https://api.glassnode.com/v1/metrics/indicators/puell_multiple',
       'https://api.glassnode.com/v1/metrics/indicators/rhodl_ratio',
       'https://api.glassnode.com/v1/metrics/market/mvrv_z_score',
       'https://api.glassnode.com/v1/metrics/indicators/sopr_adjusted',
       'https://api.glassnode.com/v1/metrics/indicators/net_unrealized_profit_loss',
       'https://api.glassnode.com/v1/metrics/mining/marketcap_thermocap_ratio'}

In [4]:
data = []
for url in urls:
    label = url.split('/')[-1]
    
    #make API request
    res = requests.get(url,params={'a': 'BTC', 'api_key': API_KEY})
    
    #convert to pandas dataframe
    df = pd.read_json(res.text, convert_dates=['t'])
    df.set_index('t', inplace = True)
    df.rename(columns={'v':label}, inplace= True)
    data.append(df)

In [5]:
# creating a dataframe from the list of results generated from the API
data_df = pd.concat(data, axis=1)
data_df

,net_unrealized_profit_loss,mvrv_z_score,price_usd_close,puell_multiple,marketcap_thermocap_ratio,exchange_net_position_change,rhodl_ratio,sopr_adjusted,reserve_risk
t,,,,,,,,,
2009-01-03,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2021-12-01,0.569798,2.671663,57182.676014,1.200194,0.000002,-24587.158110,10447.598656,1.015373,0.003950
2021-12-02,0.564203,2.606896,56448.448681,1.337253,0.000002,-34682.056808,9866.568057,0.999716,0.003895
2021-12-03,0.542734,2.374127,53765.796483,1.424949,0.000002,-26947.166530,9412.539603,0.993727,0.003831
2021-12-04,0.500216,1.998843,48962.920993,1.146894,0.000001,-18613.020117,9576.710725,0.959018,0.003356
2021-12-05,NaN,NaN,48870.596544,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data_df.to_csv('C:/Users/colli/Documents/R/Bitcoin/apidata.csv')